void print(int m,int n,const float *x);
void copy(int m, int n, const float *x, float *y);
void fc(int m, int n, const float *x, const float *A, const float *b, float *y);
void relu(int n,const float *x, float *y);
void softmax(int n,const float *x, float *y);
int inference3(const float *A, const float *b, const float *x,float * y);
int inference6(const float *A1,const float *A2,const float *A3, const float *b1,  const float *b2, const float *b3, const float *x,float * y);
void softmaxwithloss_bwd(int n, const float *y, unsigned char t, float *dEdx);
void relu_bwd(int n, const float * x, const float * dEdy, float * dEdx);
void fc_bwd(int m, int n, const float * x, const float * dEdy, const float * A, float * dEdA, float * dEdb, float * dEdx);
void backward3(const float *A, const float *b, const float *x, unsigned char t, float *y, float *dEdA, float *dEdb);
void backward6(const float *A1,const float *A2,const float *A3, const float *b1,  const float *b2, const float *b3, const float *x, unsigned char t, float *y,float *dEdA1,float *dEdA2,float *dEdA3, float *dEdb1,float *dEdb2,float *dEdb3);
void shuffle(int n, int *x);
float cross_entropy_error(const float * y, int t);
void add(int n, const float *x, float *o);
void scale(int n, float x, float *o);
void init(int n, float x, float *o);
void rand_init(int n, float *o);
